###############################################################
# Do not copy and past this file.  If you do, you won't get the
# tab in front of the clang++.  Instead download and save!
#
# Edit the compilation lines to reflect any additional .cpp
# that will need to be compiled for your code.  Example:
#
# make part1
###############################################################
.PHONY: part1 part2 part3 part4 part5 partX

part1:
	clang++ -Wall -o part1 part1.cpp Pos.cpp Node.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!

part2:
	clang++ -Wall -o part2 part2.cpp Pos.cpp Node.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!

part3:
	clang++ -Wall -o part3 part3.cpp Pos.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!

part4:
	clang++ -Wall -o part4 part4.cpp Pos.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!

part5:
	clang++ -Wall -o part5 part5.cpp Pos.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!

partX:
	clang++ -Wall -o partX partX.cpp Pos.cpp easycurses.cpp -l ncurses
########
# preceeding the clang++ must be a tab and nothing but a tab!
